#!/usr/bin/env python
# --- coding:utf-8 ---
print '中文支持'
dict={
    'name':'sun',
    'age':'18',
    'sex':'man'
}

print dict.items()

print '''获取键值对'''
for x,y in dict.items():
    if x == 'name':
        print 'my name is {y}'.format(y=y)
    elif x == 'age':
        print "i have {y}'s old".format(y=y)
    else:
        print 'i am a %s'%(y)
    print x

print '''
#########
获取键值名
#########'''
print dict.keys()
for x in dict.keys():
    print 'the keys is %s'%x

print '''获取值'''
print dict.values()
for y in dict.values():
    print 'the value is {value}'.format(value=y)