# Generated by Django 2.2.1 on 2019-06-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='b',
            field=models.ForeignKey(default='1', on_delete='CASCADE', to='myapp.Bussiness'),
            preserve_default=False,
        ),
    ]
